#if defined(__clang__)

#include <babble>
#include <babble-std>

#include <pxr/usd/usd/clipsAPI.h>

BBL_MODULE(usd) {
    // clang-format off

    bbl::Class<PXR_NS::UsdClipsAPI>("ClipsAPI")
        .ctor(bbl::Class<PXR_NS::UsdClipsAPI>::Ctor<const PXR_NS::UsdPrim &>("prim"), "from_prim")
        .ctor(bbl::Class<PXR_NS::UsdClipsAPI>::Ctor<const PXR_NS::UsdSchemaBase &>("schemaObj"), "from_schema")
        .m(&PXR_NS::UsdClipsAPI::GetSchemaAttributeNames)
        .m(&PXR_NS::UsdClipsAPI::Get)
        .m(&PXR_NS::UsdClipsAPI::GetClips)
        .m(&PXR_NS::UsdClipsAPI::SetClips)
        .m(&PXR_NS::UsdClipsAPI::GetClipSets)
        .m(&PXR_NS::UsdClipsAPI::SetClipSets)
        .m((PXR_NS::VtArray<PXR_NS::SdfAssetPath> (PXR_NS::UsdClipsAPI::*)(const std::string &) const)
            &PXR_NS::UsdClipsAPI::ComputeClipAssetPaths, "ComputeClipAssetPaths_00")
        .m((PXR_NS::VtArray<PXR_NS::SdfAssetPath> (PXR_NS::UsdClipsAPI::*)() const)
            &PXR_NS::UsdClipsAPI::ComputeClipAssetPaths, "ComputeClipAssetPaths_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(PXR_NS::VtArray<PXR_NS::SdfAssetPath> *, const std::string &) const)
            &PXR_NS::UsdClipsAPI::GetClipAssetPaths, "GetClipAssetPaths_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(PXR_NS::VtArray<PXR_NS::SdfAssetPath> *) const)
            &PXR_NS::UsdClipsAPI::GetClipAssetPaths, "GetClipAssetPaths_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const PXR_NS::VtArray<PXR_NS::SdfAssetPath> &, const std::string &))
            &PXR_NS::UsdClipsAPI::SetClipAssetPaths, "SetClipAssetPaths_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const PXR_NS::VtArray<PXR_NS::SdfAssetPath> &))
            &PXR_NS::UsdClipsAPI::SetClipAssetPaths, "SetClipAssetPaths_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(std::string *, const std::string &) const)
            &PXR_NS::UsdClipsAPI::GetClipPrimPath, "GetClipPrimPath_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(std::string *) const)
            &PXR_NS::UsdClipsAPI::GetClipPrimPath, "GetClipPrimPath_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const std::string &, const std::string &))
            &PXR_NS::UsdClipsAPI::SetClipPrimPath, "SetClipPrimPath_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const std::string &))
            &PXR_NS::UsdClipsAPI::SetClipPrimPath, "SetClipPrimPath_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(PXR_NS::VtVec2dArray *, const std::string &) const)
            &PXR_NS::UsdClipsAPI::GetClipActive, "GetClipActive_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(PXR_NS::VtVec2dArray *) const)
            &PXR_NS::UsdClipsAPI::GetClipActive, "GetClipActive_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const PXR_NS::VtVec2dArray &, const std::string &))
            &PXR_NS::UsdClipsAPI::SetClipActive, "SetClipActive_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const PXR_NS::VtVec2dArray &))
            &PXR_NS::UsdClipsAPI::SetClipActive, "SetClipActive_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(PXR_NS::VtVec2dArray *, const std::string &) const)
            &PXR_NS::UsdClipsAPI::GetClipTimes, "GetClipTimes_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(PXR_NS::VtVec2dArray *) const)
            &PXR_NS::UsdClipsAPI::GetClipTimes, "GetClipTimes_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const PXR_NS::VtVec2dArray &, const std::string &))
            &PXR_NS::UsdClipsAPI::SetClipTimes, "SetClipTimes_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const PXR_NS::VtVec2dArray &))
            &PXR_NS::UsdClipsAPI::SetClipTimes, "SetClipTimes_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(PXR_NS::SdfAssetPath *, const std::string &) const)
            &PXR_NS::UsdClipsAPI::GetClipManifestAssetPath, "GetClipManifestAssetPath_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(PXR_NS::SdfAssetPath *) const)
            &PXR_NS::UsdClipsAPI::GetClipManifestAssetPath, "GetClipManifestAssetPath_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const PXR_NS::SdfAssetPath &, const std::string &))
            &PXR_NS::UsdClipsAPI::SetClipManifestAssetPath, "SetClipManifestAssetPath_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const PXR_NS::SdfAssetPath &))
            &PXR_NS::UsdClipsAPI::SetClipManifestAssetPath, "SetClipManifestAssetPath_01")
        .m((PXR_NS::SdfLayerRefPtr (PXR_NS::UsdClipsAPI::*)(const std::string &, bool) const)
            &PXR_NS::UsdClipsAPI::GenerateClipManifest, "GenerateClipManifest_00")
        .m((PXR_NS::SdfLayerRefPtr (PXR_NS::UsdClipsAPI::*)(bool) const)
            &PXR_NS::UsdClipsAPI::GenerateClipManifest, "GenerateClipManifest_01")
        .m(&PXR_NS::UsdClipsAPI::GenerateClipManifestFromLayers)
        .m((bool (PXR_NS::UsdClipsAPI::*)(bool *, const std::string &) const)
            &PXR_NS::UsdClipsAPI::GetInterpolateMissingClipValues, "GetInterpolateMissingClipValues_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(bool *) const)
            &PXR_NS::UsdClipsAPI::GetInterpolateMissingClipValues, "GetInterpolateMissingClipValues_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(bool, const std::string &))
            &PXR_NS::UsdClipsAPI::SetInterpolateMissingClipValues, "SetInterpolateMissingClipValues_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(bool))
            &PXR_NS::UsdClipsAPI::SetInterpolateMissingClipValues, "SetInterpolateMissingClipValues_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(std::string *, const std::string &) const)
            &PXR_NS::UsdClipsAPI::GetClipTemplateAssetPath, "GetClipTemplateAssetPath_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(std::string *) const)
            &PXR_NS::UsdClipsAPI::GetClipTemplateAssetPath, "GetClipTemplateAssetPath_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const std::string &, const std::string &))
            &PXR_NS::UsdClipsAPI::SetClipTemplateAssetPath, "SetClipTemplateAssetPath_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const std::string &))
            &PXR_NS::UsdClipsAPI::SetClipTemplateAssetPath, "SetClipTemplateAssetPath_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(double *, const std::string &) const)
            &PXR_NS::UsdClipsAPI::GetClipTemplateStride, "GetClipTemplateStride_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(double *) const)
            &PXR_NS::UsdClipsAPI::GetClipTemplateStride, "GetClipTemplateStride_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const double, const std::string &))
            &PXR_NS::UsdClipsAPI::SetClipTemplateActiveOffset, "SetClipTemplateActiveOffset_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const double))
            &PXR_NS::UsdClipsAPI::SetClipTemplateActiveOffset, "SetClipTemplateActiveOffset_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(double *, const std::string &) const)
            &PXR_NS::UsdClipsAPI::GetClipTemplateActiveOffset, "GetClipTemplateActiveOffset_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(double *) const)
            &PXR_NS::UsdClipsAPI::GetClipTemplateActiveOffset, "GetClipTemplateActiveOffset_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const double, const std::string &))
            &PXR_NS::UsdClipsAPI::SetClipTemplateStride, "SetClipTemplateStride_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const double))
            &PXR_NS::UsdClipsAPI::SetClipTemplateStride, "SetClipTemplateStride_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(double *, const std::string &) const)
            &PXR_NS::UsdClipsAPI::GetClipTemplateStartTime, "GetClipTemplateStartTime_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(double *) const)
            &PXR_NS::UsdClipsAPI::GetClipTemplateStartTime, "GetClipTemplateStartTime_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const double, const std::string &))
            &PXR_NS::UsdClipsAPI::SetClipTemplateStartTime, "SetClipTemplateStartTime_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const double))
            &PXR_NS::UsdClipsAPI::SetClipTemplateStartTime, "SetClipTemplateStartTime_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(double *, const std::string &) const)
            &PXR_NS::UsdClipsAPI::GetClipTemplateEndTime, "GetClipTemplateEndTime_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(double *) const)
            &PXR_NS::UsdClipsAPI::GetClipTemplateEndTime, "GetClipTemplateEndTime_01")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const double, const std::string &))
            &PXR_NS::UsdClipsAPI::SetClipTemplateEndTime, "SetClipTemplateEndTime_00")
        .m((bool (PXR_NS::UsdClipsAPI::*)(const double))
            &PXR_NS::UsdClipsAPI::SetClipTemplateEndTime, "SetClipTemplateEndTime_01")
    ;
}

#endif

